Correction "Client network socket disconnected before secure TLS..."
A typical build process for client-side JavaScript in the browser consists of consecutive transformations such as grouping, transpiling, and minification. The goal is to group the entire application into a single file that is as small as possible so that it can be efficiently delivered to the browser.
Error: remote: Locales did not loaded: Error: Client network socket disconnected before secure TLS connection was established
correction: 
{
  "presets": ["es2015"],
  "compact": true
}